INSERT INTO sucursales.sucursal (nombre, direccion), VALUES('Sucursal Centro1','en el centro');
INSERT INTO sucursales.sucursal (nombre, direccion), VALUES('Sucursal Centro2','en el centro2');



INSERT INTO sucursales.bodegas (nombre, direccion), VALUES('Bodega Sucursal Centro1','en el centro bodega');
INSERT INTO sucursales.bodegas (nombre, direccion), VALUES('Bodega Sucursal Centro2','en el centro2 bodega');



INSERT into sucursales.bodegas_sucursal VALUES(2,2);

INSERT into sucursales.bodegas_sucursal VALUES(3,3);


-- ingresando productos de bodega 1 

INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 29, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 30, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 31, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 32, 15);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 33, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 34, 60);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 35, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 36, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 37, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 38, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 39, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 40, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 41, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 42, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 43, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 44, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 45, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 46, 17);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 47, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 48, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 49, 10);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 50, 55);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 51, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 52, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 53, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 54, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 55, 12);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 56, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 57, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 58, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 59, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 60, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 61, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 62, 31);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 63, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 64, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 65, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 66, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 67, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 68, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 69, 55);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 70, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 71, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 72, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 73, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 74, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 75, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 76, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 77, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 78, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 79, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 80, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 81, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 82, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 83, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 84, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 85, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 86, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 87, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 88, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 89, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 90, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 91, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 92, 32);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 93, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 94, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 95, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 96, 15);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 97, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 98, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 99, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 100, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 101, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 102, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 103, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 104, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 105, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 106, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 107, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 108, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 109, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 110, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 111, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 112, 32);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 113, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 114, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 115, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 116, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 117, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 118, 17);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 119, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 120, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 121, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 122, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 123, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (1, 124, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 29, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 30, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 31, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 32, 15);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 33, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 34, 60);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 35, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 36, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 37, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 38, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 39, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 40, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 41, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 42, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 43, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 44, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 45, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 46, 17);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 47, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 48, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 49, 10);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 50, 55);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 51, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 52, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 53, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 54, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 55, 12);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 56, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 57, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 58, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 59, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 60, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 61, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 62, 31);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 63, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 64, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 65, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 66, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 67, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 68, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 69, 55);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 70, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 71, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 72, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 73, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 74, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 75, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 76, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 77, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 78, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 79, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 80, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 81, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 82, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 83, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 84, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 85, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 86, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 87, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 88, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 89, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 90, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 91, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 92, 32);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 93, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 94, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 95, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 96, 15);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 97, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 98, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 99, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 100, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 101, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 102, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (2, 103, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 49, 10);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 50, 55);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 51, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 52, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 53, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 54, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 55, 12);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 56, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 57, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 58, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 59, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 60, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 61, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 62, 31);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 63, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 64, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 65, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 66, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 67, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3,68, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 69, 55);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 70, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 71, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 72, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 73, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 74, 20);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 75, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 76, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 77, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 78, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 79, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 80, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 81, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 82, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 83, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 84, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 85, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 86, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 87, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 88, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 89, 30);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 90, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 91, 40);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 92, 32);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 93, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 94, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 95, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 96, 15);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 97, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 98, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 99, 35);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 100, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 101, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 102, 25);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 103, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 104, 27);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 105, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 106, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 107, 21);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 108, 18);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 109, 36);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 110, 19);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 111, 23);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 112, 32);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 113, 45);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 114, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 115, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 116, 29);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 117, 34);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 118, 17);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 119, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 120, 33);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 121, 22);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 122, 28);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 123, 50);
INSERT INTO sucursales.catalogo_bodega (codigo_bodega, codigo_producto, existencias) VALUES (3, 124, 27);


INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 29, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 30, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 31, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 32, 15);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 33, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 34, 60);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 35, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 36, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 37, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 38, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 39, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 40, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 41, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 42, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 43, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 44, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 45, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 46, 17);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 47, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 48, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 49, 10);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 50, 55);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 51, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 52, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 53, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 54, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 55, 12);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 56, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 57, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 58, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 59, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 60, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 61, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 62, 31);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 63, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 64, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 65, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 66, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 67, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 68, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 69, 55);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 70, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 71, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 72, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 73, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 74, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 75, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 76, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 77, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 78, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 79, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 80, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 81, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 82, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 83, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 84, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 85, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 86, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 87, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 88, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 89, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 90, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 91, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 92, 32);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 93, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 94, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 95, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 96, 15);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 97, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 98, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 99, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 100, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 101, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 102, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 103, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 104, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 105, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 106, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 107, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 108, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 109, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 110, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 111, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 112, 32);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 113, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 114, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 115, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 116, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 117, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 118, 17);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 119, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 120, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 121, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 122, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 123, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (1, 124, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 29, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 30, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 31, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 32, 15);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 33, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 34, 60);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 35, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 36, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 37, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 38, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 39, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 40, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 41, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 42, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 43, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 44, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 45, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 46, 17);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 47, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 48, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 49, 10);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 50, 55);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 51, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 52, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 53, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 54, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 55, 12);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 56, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 57, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 58, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 59, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 60, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 61, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 62, 31);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 63, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 64, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 65, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 66, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 67, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 68, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 69, 55);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 70, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 71, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 72, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 73, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 74, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 75, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 76, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 77, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 78, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 79, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 80, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 81, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 82, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 83, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 84, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 85, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 86, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 87, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 88, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 89, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 90, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 91, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 92, 32);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 93, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 94, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 95, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 96, 15);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 97, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 98, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 99, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 100, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 101, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 102, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (2, 103, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 49, 10);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 50, 55);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 51, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 52, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 53, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 54, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 55, 12);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 56, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 57, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 58, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 59, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 60, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 61, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 62, 31);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 63, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 64, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 65, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 66, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 67, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3,68, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 69, 55);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 70, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 71, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 72, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 73, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 74, 20);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 75, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 76, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 77, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 78, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 79, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 80, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 81, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 82, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 83, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 84, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 85, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 86, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 87, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 88, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 89, 30);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 90, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 91, 40);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 92, 32);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 93, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 94, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 95, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 96, 15);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 97, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 98, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 99, 35);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 100, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 101, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 102, 25);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 103, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 104, 27);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 105, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 106, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 107, 21);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 108, 18);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 109, 36);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 110, 19);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 111, 23);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 112, 32);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 113, 45);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 114, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 115, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 116, 29);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 117, 34);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 118, 17);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 119, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 120, 33);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 121, 22);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 122, 28);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 123, 50);
INSERT INTO sucursales.catalogo_sucursal (codigo_sucursal, codigo_producto, existencias) VALUES (3, 124, 27);


INSERT INTO ventas.clientes VALUES (10,'cliente 10', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (11,'cliente 11', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (12,'cliente 12', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (13,'cliente 13', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (14,'cliente 14', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (15,'cliente 15', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (16,'cliente 16', 'correo10@correo.com','direccion10');
INSERT INTO ventas.clientes VALUES (17,'cliente 17', 'correo10@correo.com','direccion10');


INSERT into empleados.cajeros (nombre, usuario, contrasena, correo,codigo_sucursal, codigo_caja) VALUES ('caja 1','caja1','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',2,10);
INSERT into empleados.cajeros (nombre, usuario, contrasena, correo,codigo_sucursal, codigo_caja) VALUES ('caja 2','caja3','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',2,11);
INSERT into empleados.cajeros (nombre, usuario, contrasena, correo,codigo_sucursal, codigo_caja) VALUES ('caja 3','caja3','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',3,1);
INSERT into empleados.cajeros (nombre, usuario, contrasena, correo,codigo_sucursal, codigo_caja) VALUES ('caja 4','caja4','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',3,10);
INSERT into empleados.cajeros (nombre, usuario, contrasena, correo,codigo_sucursal, codigo_caja) VALUES ('caja 11','caja11','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',1,5);


    INSERT INTO empleados.bodegueros (nombre, usuario, contrasena,correo,codigo_bodega) 
	VALUES ('bodegas 2', 'usuariobodega2','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',2);

INSERT INTO empleados.bodegueros (nombre, usuario, contrasena,correo,codigo_bodega) 
	VALUES ('bodegas 3', 'usuariobodega3','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',3);
    INSERT INTO empleados.inventario (nombre, usuario,contrasena,correo,codigo_sucursal)
VALUES ('inventario2','inventario2','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',2);
INSERT INTO empleados.inventario (nombre, usuario,contrasena,correo,codigo_sucursal)
VALUES ('inventario3','inventario3','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
	'correo',3);








